[2024-12-29T11:23:13.232+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-29T11:23:13.259+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_monitor_v1.check_stock_price manual__2024-12-29T11:23:10.737396+00:00 [queued]>
[2024-12-29T11:23:13.267+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_monitor_v1.check_stock_price manual__2024-12-29T11:23:10.737396+00:00 [queued]>
[2024-12-29T11:23:13.269+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-29T11:23:13.281+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_stock_price> on 2024-12-29 11:23:10.737396+00:00
[2024-12-29T11:23:13.287+0000] {standard_task_runner.py:72} INFO - Started process 9966 to run task
[2024-12-29T11:23:13.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_monitor_v1', 'check_stock_price', 'manual__2024-12-29T11:23:10.737396+00:00', '--job-id', '1040', '--raw', '--subdir', 'DAGS_FOLDER/email_generation.py', '--cfg-path', '/tmp/tmpx8ln01i6']
[2024-12-29T11:23:13.358+0000] {standard_task_runner.py:105} INFO - Job 1040: Subtask check_stock_price
[2024-12-29T11:23:13.582+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_monitor_v1.check_stock_price manual__2024-12-29T11:23:10.737396+00:00 [running]> on host 95d98a98d27d
[2024-12-29T11:23:13.800+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='stock_price_monitor_v1' AIRFLOW_CTX_TASK_ID='check_stock_price' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T11:23:10.737396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-29T11:23:10.737396+00:00'
[2024-12-29T11:23:13.803+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-29T11:23:13.804+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-29T11:23:13.805+0000] {logging_mixin.py:190} INFO - Current task name:check_stock_price state:running start_date:2024-12-29 11:23:13.260747+00:00
[2024-12-29T11:23:13.806+0000] {logging_mixin.py:190} INFO - Dag name:stock_price_monitor_v1 and current dag run status:running
[2024-12-29T11:23:13.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-29T11:23:13.840+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-12-29T11:23:13.856+0000] {sql.py:544} INFO - Running statement: select 1, parameters: None
[2024-12-29T11:23:13.858+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-29T11:23:13.862+0000] {logging_mixin.py:190} INFO - Connection successful
[2024-12-29T11:23:13.863+0000] {logging_mixin.py:190} INFO - Checking stock price...
[2024-12-29T11:23:13.869+0000] {sql.py:544} INFO - Running statement: 
        SELECT ticker, "Current Price" as current_price 
        FROM public.live_stock 
        LIMIT 1;
    , parameters: None
[2024-12-29T11:23:13.886+0000] {sql.py:553} INFO - Rows affected: 1
[2024-12-29T11:23:13.888+0000] {logging_mixin.py:190} INFO - Records: [('AAPL', '$255.59')]
[2024-12-29T11:23:13.919+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/email_generation.py", line 50, in check_stock_price
    if price < threshold:
TypeError: '<' not supported between instances of 'str' and 'int'
[2024-12-29T11:23:13.934+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-29T11:23:13.935+0000] {logging_mixin.py:190} INFO - Task start:2024-12-29 11:23:13.260747+00:00 end:2024-12-29 11:23:13.934207+00:00 duration:0.67346
[2024-12-29T11:23:13.936+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): check_stock_price> dag:<DAG: stock_price_monitor_v1> dagrun:<DagRun stock_price_monitor_v1 @ 2024-12-29 11:23:10.737396+00:00: manual__2024-12-29T11:23:10.737396+00:00, state:running, queued_at: 2024-12-29 11:23:10.748722+00:00. externally triggered: True>
[2024-12-29T11:23:13.937+0000] {logging_mixin.py:190} INFO - Failure caused by '<' not supported between instances of 'str' and 'int'
[2024-12-29T11:23:13.938+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_monitor_v1, task_id=check_stock_price, run_id=manual__2024-12-29T11:23:10.737396+00:00, execution_date=20241229T112310, start_date=20241229T112313, end_date=20241229T112313
[2024-12-29T11:23:13.954+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-29T11:23:13.955+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1040 for task check_stock_price ('<' not supported between instances of 'str' and 'int'; 9966)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/email_generation.py", line 50, in check_stock_price
    if price < threshold:
TypeError: '<' not supported between instances of 'str' and 'int'
[2024-12-29T11:23:14.003+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-29T11:23:14.026+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-29T11:23:14.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
