[2024-12-27T18:07:32.963+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-27T18:07:32.985+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_pipeline.realtime_pipeline scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2024-12-27T18:07:32.996+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_pipeline.realtime_pipeline scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2024-12-27T18:07:32.997+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-27T18:07:33.017+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): realtime_pipeline> on 2024-12-26 00:00:00+00:00
[2024-12-27T18:07:33.025+0000] {standard_task_runner.py:72} INFO - Started process 780 to run task
[2024-12-27T18:07:33.028+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'realtime_pipeline', 'realtime_pipeline', 'scheduled__2024-12-26T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/realtime_ingestion.py', '--cfg-path', '/tmp/tmpxtxg34lk']
[2024-12-27T18:07:33.031+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask realtime_pipeline
[2024-12-27T18:07:33.087+0000] {task_command.py:467} INFO - Running <TaskInstance: realtime_pipeline.realtime_pipeline scheduled__2024-12-26T00:00:00+00:00 [running]> on host c36613fa3dab
[2024-12-27T18:07:33.181+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='realtime_pipeline' AIRFLOW_CTX_TASK_ID='realtime_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-26T00:00:00+00:00'
[2024-12-27T18:07:33.184+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-27T18:07:33.186+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-27T18:07:33.187+0000] {logging_mixin.py:190} INFO - Current task name:realtime_pipeline state:running start_date:2024-12-27 18:07:32.986806+00:00
[2024-12-27T18:07:33.189+0000] {logging_mixin.py:190} INFO - Dag name:realtime_pipeline and current dag run status:running
[2024-12-27T18:07:33.190+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-27T18:07:37.066+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-27T18:07:37.068+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2024-12-27T18:07:37.069+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-12-27T18:07:40.773+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-27T18:07:40.775+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2024-12-27T18:07:40.777+0000] {data_ingestion.py:76} ERROR - Couldn't create producer: NoBrokersAvailable
[2024-12-27T18:07:44.493+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-27T18:07:44.494+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2024-12-27T18:07:44.495+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-12-27T18:07:48.382+0000] {conn.py:1527} WARNING - DNS lookup failed for kafka:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-27T18:07:48.384+0000] {conn.py:315} ERROR - DNS lookup failed for kafka:29092 (0)
[2024-12-27T18:07:48.385+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 6, in realtime_pipeline
    data_ingestion(topic_name, ticker)
  File "/opt/airflow/etl/data_ingestion.py", line 116, in data_ingestion
    topic = topic_creation(topic_name)
  File "/opt/airflow/etl/data_ingestion.py", line 82, in topic_creation
    admin_client = KafkaAdminClient(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/admin/client.py", line 208, in __init__
    self._client = KafkaClient(metrics=self._metrics,
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-12-27T18:07:48.409+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-27T18:07:48.411+0000] {logging_mixin.py:190} INFO - Task start:2024-12-27 18:07:32.986806+00:00 end:2024-12-27 18:07:48.409513+00:00 duration:15.422707
[2024-12-27T18:07:48.412+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): realtime_pipeline> dag:<DAG: realtime_pipeline> dagrun:<DagRun realtime_pipeline @ 2024-12-26 00:00:00+00:00: scheduled__2024-12-26T00:00:00+00:00, state:running, queued_at: 2024-12-27 17:51:21.231335+00:00. externally triggered: False>
[2024-12-27T18:07:48.413+0000] {logging_mixin.py:190} INFO - Failure caused by NoBrokersAvailable
[2024-12-27T18:07:48.414+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=realtime_pipeline, task_id=realtime_pipeline, run_id=scheduled__2024-12-26T00:00:00+00:00, execution_date=20241226T000000, start_date=20241227T180732, end_date=20241227T180748
[2024-12-27T18:07:48.424+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-27T18:07:48.425+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 107 for task realtime_pipeline (NoBrokersAvailable; 780)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 6, in realtime_pipeline
    data_ingestion(topic_name, ticker)
  File "/opt/airflow/etl/data_ingestion.py", line 116, in data_ingestion
    topic = topic_creation(topic_name)
  File "/opt/airflow/etl/data_ingestion.py", line 82, in topic_creation
    admin_client = KafkaAdminClient(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/admin/client.py", line 208, in __init__
    self._client = KafkaClient(metrics=self._metrics,
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-12-27T18:07:48.470+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-27T18:07:48.482+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-27T18:07:48.484+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
