[2025-01-01T18:25:55.633+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T18:25:55.649+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_dump_pipeline.realtime_pipeline scheduled__2024-12-30T09:05:00+00:00 [queued]>
[2025-01-01T18:25:55.660+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_dump_pipeline.realtime_pipeline scheduled__2024-12-30T09:05:00+00:00 [queued]>
[2025-01-01T18:25:55.662+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-01T18:25:55.677+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): realtime_pipeline> on 2024-12-30 09:05:00+00:00
[2025-01-01T18:25:55.688+0000] {standard_task_runner.py:72} INFO - Started process 92356 to run task
[2025-01-01T18:25:55.693+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'realtime_dump_pipeline', 'realtime_pipeline', 'scheduled__2024-12-30T09:05:00+00:00', '--job-id', '1492', '--raw', '--subdir', 'DAGS_FOLDER/realtime_data_dump.py', '--cfg-path', '/tmp/tmpkrm1kjsr']
[2025-01-01T18:25:55.697+0000] {standard_task_runner.py:105} INFO - Job 1492: Subtask realtime_pipeline
[2025-01-01T18:25:55.755+0000] {task_command.py:467} INFO - Running <TaskInstance: realtime_dump_pipeline.realtime_pipeline scheduled__2024-12-30T09:05:00+00:00 [running]> on host 95d98a98d27d
[2025-01-01T18:25:55.850+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='realtime_dump_pipeline' AIRFLOW_CTX_TASK_ID='realtime_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T09:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T09:05:00+00:00'
[2025-01-01T18:25:55.852+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-01T18:25:55.854+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-01T18:25:55.855+0000] {logging_mixin.py:190} INFO - Current task name:realtime_pipeline state:running start_date:2025-01-01 18:25:55.651374+00:00
[2025-01-01T18:25:55.856+0000] {logging_mixin.py:190} INFO - Dag name:realtime_dump_pipeline and current dag run status:running
[2025-01-01T18:25:55.858+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T18:26:01.756+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7fef307bd510>
[2025-01-01T18:26:01.757+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2025-01-01T18:26:02.993+0000] {logging_mixin.py:190} INFO - Reading from topic stock
[2025-01-01T18:26:03.428+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2025-01-01T18:26:03.430+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 38913)
[2025-01-01T18:26:10.980+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 12, in data_dump_pipeline
    spark_streaming(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 172, in spark_streaming
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = fdeb103c-dd08-46bf-a737-8e42664083ca, runId = 937ec0db-d8e0-4ff9-b9b3-bf5d332a7b98] terminated with exception: Failed to create new KafkaAdminClient
[2025-01-01T18:26:10.996+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-01T18:26:10.997+0000] {logging_mixin.py:190} INFO - Task start:2025-01-01 18:25:55.651374+00:00 end:2025-01-01 18:26:10.995423+00:00 duration:15.344049
[2025-01-01T18:26:10.998+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): realtime_pipeline> dag:<DAG: realtime_dump_pipeline> dagrun:<DagRun realtime_dump_pipeline @ 2024-12-30 09:05:00+00:00: scheduled__2024-12-30T09:05:00+00:00, state:running, queued_at: 2025-01-01 18:18:30.800403+00:00. externally triggered: False>
[2025-01-01T18:26:11.001+0000] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = fdeb103c-dd08-46bf-a737-8e42664083ca, runId = 937ec0db-d8e0-4ff9-b9b3-bf5d332a7b98] terminated with exception: Failed to create new KafkaAdminClient
[2025-01-01T18:26:11.003+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=realtime_dump_pipeline, task_id=realtime_pipeline, run_id=scheduled__2024-12-30T09:05:00+00:00, execution_date=20241230T090500, start_date=20250101T182555, end_date=20250101T182610
[2025-01-01T18:26:11.018+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T18:26:11.020+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1492 for task realtime_pipeline ([STREAM_FAILED] Query [id = fdeb103c-dd08-46bf-a737-8e42664083ca, runId = 937ec0db-d8e0-4ff9-b9b3-bf5d332a7b98] terminated with exception: Failed to create new KafkaAdminClient; 92356)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 12, in data_dump_pipeline
    spark_streaming(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 172, in spark_streaming
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = fdeb103c-dd08-46bf-a737-8e42664083ca, runId = 937ec0db-d8e0-4ff9-b9b3-bf5d332a7b98] terminated with exception: Failed to create new KafkaAdminClient
[2025-01-01T18:26:11.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-01T18:26:11.079+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-01T18:26:11.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
