[2024-12-28T14:57:17.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-28T14:57:17.841+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_dump_pipeline.realtime_pipeline manual__2024-12-28T14:57:15.886637+00:00 [queued]>
[2024-12-28T14:57:17.849+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_dump_pipeline.realtime_pipeline manual__2024-12-28T14:57:15.886637+00:00 [queued]>
[2024-12-28T14:57:17.851+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-28T14:57:17.863+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): realtime_pipeline> on 2024-12-28 14:57:15.886637+00:00
[2024-12-28T14:57:17.871+0000] {standard_task_runner.py:72} INFO - Started process 3626 to run task
[2024-12-28T14:57:17.874+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'realtime_dump_pipeline', 'realtime_pipeline', 'manual__2024-12-28T14:57:15.886637+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/realtime_data_dump.py', '--cfg-path', '/tmp/tmps9o9vmf5']
[2024-12-28T14:57:17.876+0000] {standard_task_runner.py:105} INFO - Job 244: Subtask realtime_pipeline
[2024-12-28T14:57:17.913+0000] {task_command.py:467} INFO - Running <TaskInstance: realtime_dump_pipeline.realtime_pipeline manual__2024-12-28T14:57:15.886637+00:00 [running]> on host 24435936fa97
[2024-12-28T14:57:17.976+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haziq' AIRFLOW_CTX_DAG_ID='realtime_dump_pipeline' AIRFLOW_CTX_TASK_ID='realtime_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T14:57:15.886637+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-28T14:57:15.886637+00:00'
[2024-12-28T14:57:17.978+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-28T14:57:17.979+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-28T14:57:17.980+0000] {logging_mixin.py:190} INFO - Current task name:realtime_pipeline state:running start_date:2024-12-28 14:57:17.842396+00:00
[2024-12-28T14:57:17.981+0000] {logging_mixin.py:190} INFO - Dag name:realtime_dump_pipeline and current dag run status:running
[2024-12-28T14:57:17.982+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-28T14:57:21.802+0000] {logging_mixin.py:190} INFO - <pyspark.sql.session.SparkSession object at 0x7f631bf36e30>
[2024-12-28T14:57:21.804+0000] {logging_mixin.py:190} INFO - Spark session created successfully
[2024-12-28T14:57:22.999+0000] {logging_mixin.py:190} INFO - Reading from topic stock
[2024-12-28T14:57:23.230+0000] {java_gateway.py:2273} INFO - Callback Server Starting
[2024-12-28T14:57:23.232+0000] {java_gateway.py:2275} INFO - Socket listening on ('127.0.0.1', 39291)
[2024-12-28T14:57:27.333+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 12, in data_dump_pipeline
    spark_streaming(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 161, in spark_streaming
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = cbc88d81-c807-41ea-b8b4-0c4188f112b6, runId = cb7783c2-cf12-4963-befb-790bf19b9da8] terminated with exception: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2024-12-28T14:57:27.362+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-28T14:57:27.363+0000] {logging_mixin.py:190} INFO - Task start:2024-12-28 14:57:17.842396+00:00 end:2024-12-28 14:57:27.361755+00:00 duration:9.519359
[2024-12-28T14:57:27.365+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): realtime_pipeline> dag:<DAG: realtime_dump_pipeline> dagrun:<DagRun realtime_dump_pipeline @ 2024-12-28 14:57:15.886637+00:00: manual__2024-12-28T14:57:15.886637+00:00, state:running, queued_at: 2024-12-28 14:57:15.899641+00:00. externally triggered: True>
[2024-12-28T14:57:27.369+0000] {logging_mixin.py:190} INFO - Failure caused by [STREAM_FAILED] Query [id = cbc88d81-c807-41ea-b8b4-0c4188f112b6, runId = cb7783c2-cf12-4963-befb-790bf19b9da8] terminated with exception: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2024-12-28T14:57:27.371+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=realtime_dump_pipeline, task_id=realtime_pipeline, run_id=manual__2024-12-28T14:57:15.886637+00:00, execution_date=20241228T145715, start_date=20241228T145717, end_date=20241228T145727
[2024-12-28T14:57:27.397+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-28T14:57:27.399+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 244 for task realtime_pipeline ([STREAM_FAILED] Query [id = cbc88d81-c807-41ea-b8b4-0c4188f112b6, runId = cb7783c2-cf12-4963-befb-790bf19b9da8] terminated with exception: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.; 3626)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipeline/pipeline.py", line 12, in data_dump_pipeline
    spark_streaming(topic, BROKER)
  File "/opt/airflow/etl/data_dump_v2.py", line 161, in spark_streaming
    query.awaitTermination()
  File "/opt/spark/python/pyspark/sql/streaming/query.py", line 221, in awaitTermination
    return self._jsq.awaitTermination()
  File "/home/airflow/.local/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/opt/spark/python/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.StreamingQueryException: [STREAM_FAILED] Query [id = cbc88d81-c807-41ea-b8b4-0c4188f112b6, runId = cb7783c2-cf12-4963-befb-790bf19b9da8] terminated with exception: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2024-12-28T14:57:27.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-28T14:57:27.466+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-28T14:57:27.469+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
